services:
  db:
    image: postgres:16
    container_name: csbot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
      PGPORT: ${PGPORT}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    profiles: ["local"]

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE} -p ${PGPORT}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
